### ISSUE TITLE
Bug on order v 1.9.6 + GLPI v 0.85.5 - Invoice section

### ISSUE THREAD

**Issue by GlpiUser** [pluginsGLPI/order#116]
Hi everyone, 
there is a bug when adding a new invoice or changing statut. 
![image](https://cloud.githubusercontent.com/assets/28047709/25430241/328bf12a-2a7c-11e7-9a47-8e8d2c493f73.png)
I got this error message "Parse error: syntax error, unexpected '[', expecting ')' in C:\xampp\htdocs\glpi\plugins\order\front\bill.form.php on line 92"

To fix it edit the line "$bill->display([]);" by "$bill->show();"
but maybe there is something else to change ?

**Comment by cedric-anne** [comment]
Hi,

The problem is due to your PHP version. This `[]` syntax has been introduced in PHP 5.4, so if you are running under a lower version, it triggers this parsing error.

The 1.9.6 version of this plugin should not be considered as compatible with GLPI 0.85 as PHP 5.4 version was introduced as minimal requirement in GLPI 0.90.

However, we will not put back compatibility with PHP < 5.4.

Regards
